export const accessibilityColors = {
  normal: {
    "--background-primary": "#ffffff",
    "--background-secondary": "#f8f9fa",
    "--text-primary": "#000000",
    "--text-secondary": "#6c757d",
    "--button-primary": "#007bff",
    "--button-secondary": "#6c757d",
    "--button-success": "#28a745",
    "--button-danger": "#dc3545",
    "--button-warning": "#ffc107",
    "--link": "#007bff",
    "--border": "#dee2e6",
    "--navbar": "#343a40",
    "--navbar-text": "#ffffff",
    "--card-bg": "#ffffff",
    "--input-bg": "#ffffff",
    "--input-border": "#ced4da",
    "--table-border": "#dee2e6",
    "--table-stripe": "#f2f2f2",
    "--favorite-active": "#ff3366",
  },

  protanopia: {
    "--background-primary": "#f0f7ff",
    "--background-secondary": "#e6f3ff",
    "--text-primary": "#00264d",
    "--text-secondary": "#666666",
    "--button-primary": "#0066cc",
    "--button-secondary": "#ffd700",
    "--button-success": "#ffdd00",
    "--button-danger": "#0000ff",
    "--button-warning": "#ffff00",
    "--link": "#0066cc",
    "--border": "#0066cc",
    "--navbar": "#003366",
    "--navbar-text": "#ffffff",
    "--card-bg": "#ffffff",
    "--input-bg": "#ffffff",
    "--input-border": "#000000",
    "--table-border": "#000000",
    "--table-stripe": "#e6e6e6",
    "--favorite-active": "#ffd700",
  },

  deuteranopia: {
    "--background-primary": "#fff7e6",
    "--background-secondary": "#fff0cc",
    "--text-primary": "#000066",
    "--text-secondary": "#666666",
    "--button-primary": "#0000ff",
    "--button-secondary": "#ffcc00",
    "--button-success": "#ffff00",
    "--button-danger": "#8000ff",
    "--button-warning": "#ffaa00",
    "--link": "#0000ff",
    "--border": "#0000cc",
    "--navbar": "#000099",
    "--navbar-text": "#ffffff",
    "--card-bg": "#ffffff",
    "--input-bg": "#ffffff",
    "--input-border": "#000000",
    "--table-border": "#000000",
    "--table-stripe": "#e6e6e6",
    "--favorite-active": "#0000ff",
  },

  tritanopia: {
    "--background-primary": "#fff5f5",
    "--background-secondary": "#ffe6e6",
    "--text-primary": "#660000",
    "--text-secondary": "#666666",
    "--button-primary": "#cc0000",
    "--button-secondary": "#00cc00",
    "--button-success": "#00ff00",
    "--button-danger": "#ff0000",
    "--button-warning": "#ff6600",
    "--link": "#ff0000",
    "--border": "#cc0000",
    "--navbar": "#990000",
    "--navbar-text": "#ffffff",
    "--card-bg": "#ffffff",
    "--input-bg": "#ffffff",
    "--input-border": "#000000",
    "--table-border": "#000000",
    "--table-stripe": "#e6e6e6",
    "--favorite-active": "#ff0000",
  },

  achromatopsia: {
    "--background-primary": "#ffffff",
    "--background-secondary": "#f0f0f0",
    "--text-primary": "#000000",
    "--text-secondary": "#404040",
    "--button-primary": "#1a1a1a",
    "--button-secondary": "#808080",
    "--button-success": "#1a1a1a",
    "--button-danger": "#000000",
    "--button-warning": "#666666",
    "--link": "#000000",
    "--border": "#404040",
    "--navbar": "#000000",
    "--navbar-text": "#ffffff",
    "--card-bg": "#ffffff",
    "--input-bg": "#ffffff",
    "--input-border": "#000000",
    "--table-border": "#000000",
    "--table-stripe": "#e6e6e6",
    "--favorite-active": "#000000",
  },
};
